### ISSUE TITLE
Only-Run-Once-Appliance don't work

### ISSUE THREAD

**Issue by ioniks** [InventoCasa/ha-advanced-blueprints#54]
Hi,

When i set Only-Run-Once-Appliance to on, when i set to off the entity, the automatisation set to On a few time after if they have solar.

How i can have only one on for a day ?

Thanks

**Comment by faebsche91** [comment]
I have same issue. Is there a solution ?

**Comment by ioniks** [comment]
I have create a trigger when it's activated and deactivated it after, and re activated it the next morning.

**Comment by faebsche91** [comment]
So you don’t use the „only-run-once-appliance“ anymore ?

**Comment by ioniks** [comment]
Yes i don't use it

**Comment by Maik7** [comment]
@ioniks 

> Hi,
> 
> When i set Only-Run-Once-Appliance to on, when i set to off the entity, the automatisation set to On a few time after if they have solar.

you have to turn the automation off, and then switch off the entity:
```
service: automation.turn_off
target:
  entity_id: automation.nameofautomation
data:  {}
```
 
 (you can already turn the automation off, as soon as the script had switched your entity on, e. g. by an automation which is triggered if your entity is switched on)

> How i can have only one on for a day ?

you can create another automation to activate your automation once a day. In this example at 7 o clock:
```

mode: single
trigger:
  - platform: time_pattern
    hours: "07"
    minutes: "00"
    seconds: "00"
condition: []
action:
  - service: automation.turn_on
    target:
      entity_id: automation.nameofautomation
    data: {}

```

(not tested, but should work)

> Thanks

welcome :-)
