### ISSUE TITLE
Dynamic current control is exceed my solar production

### ISSUE THREAD

**Issue by liouma** [InventoCasa/ha-advanced-blueprints#94]
The automation with dynamic current control adjust my electric vehicule charge power too high (16A) so I exceed my production and need to import power (2kW) from the grid.

I have a setup with 6kWC Huawei solar panels, a 5kWh battery, an electric car with a charger adjustable from 6A to 16A. I noticed many times that the dynamic current changes the charging value but not as expected.

I have an automation to adjust my car charger with a dynamic current control setting:
```
alias: PV Charge automatique voiture
description: PV Excess
use_blueprint:
  path: pv_excess_control/pv_excess_control.yaml
  input:
    automation_id: pv_charge_automatique_voiture
    appliance_priority: "{{states('input_number.pv_priorite_charge_voiture') | int (1) }}"
    pv_power: sensor.inverter_input_power
    grid_voltage: 240
    home_battery_level: sensor.battery_state_of_capacity
    min_home_battery_level: 15
    home_battery_capacity: 5
    solar_production_forecast: sensor.energy_production_today_remaining_total
    min_current: 6
    max_current: 16
    defined_current: 8
    actual_power: sensor.voiture_mesure_charge_puissance
    appliance_switch: switch.voiture_commande_charge
    appliance_switch_interval: 45
    load_power: sensor.power_house_load
    export_power: sensor.power_export
    dynamic_current_appliance: true
    appliance_current_set_entity: number.ev_charger_set_charge_current
```

In the current example, I produce 2.7W, my house use 4800W including 3750W for the car so I need to import 2100W
So I would expect the automation to set the charging current to a lower value not to import so much energy from the grid (EDF in the picture). But the charging is set to 16A so the car (voiture) consumtion is high as you can see:

![image](https://github.com/user-attachments/assets/fc9ff48f-68e8-4330-a8bf-51b51dcb64e7)

I attached the logs:
[home-assistant_pyscript_2024-12-11T12-29-49.375Z.log](https://github.com/user-attachments/files/18095620/home-assistant_pyscript_2024-12-11T12-29-49.375Z.log)

EDIT: the priority is > 1000 so the automation behavior is normal.
